let suggestions = [
     "Best Movies",
     "Best Series",
     "Best Youtuber",
     "Best Software Company",
     "Best Songs",
     "Best Designer",
     "Best content",
     "Best Freelancer",
     "Web Development",
     "Developer",
     "Anime",
     "Coding Language",
     "Episodes",
     "Freelancer",
     "Grammerly",
     "HTML",
     "Innovations",
     "JavaScript",
     "Kotlin",
     "Languages",
     "MangoDB",
     "Nodejs",
     "OOps",
     "Python Progarmming",
     "Quora",
     "R Programming",
     "Scripting",
     "Typing",
     "Uml diagram",
     "Vue",
     "What is best Language?",
     "XML",
     "Youtube",
     "Zoom"

];